version: '3'

services:
  python3:
    # restart: always
    build: .
    tty: true
    volumes:
      - .:/root/workspace
      - ~/.Xauthority:/root/.Xauthority
    environment:
      - DISPLAY=host.docker.internal:0
